refactor: separate dev/prod requirements

diff --git a/.github/actions/tests/python/action.yml b/.github/actions/tests/python/action.yml
--- a/.github/actions/tests/python/action.yml
+++ b/.github/actions/tests/python/action.yml
@@ -30,32 +30,32 @@ runs:
     - name: Check for openai in requirements
       shell: bash
       run: |
-        if ! grep -q "openai" ./requirements.txt; then
-          echo "openai not found in requirements.txt" >&2
+        if ! grep -q "openai" requirements/prod.txt; then
+          echo "openai not found in requirements/prod.txt" >&2
           exit 1
         fi
 
     - name: Check for langchain in requirements
       shell: bash
       run: |
-        if ! grep -q "langchain" ./requirements.txt; then
-          echo "langchain not found in requirements.txt" >&2
+        if ! grep -q "langchain" requirements/prod.txt; then
+          echo "langchain not found in requirements/prod.txt" >&2
           exit 1
         fi
 
     - name: Check for langchain-experimental in requirements
       shell: bash
       run: |
-        if ! grep -q "langchain-experimental" ./requirements.txt; then
-          echo "langchain-experimental not found in requirements.txt" >&2
+        if ! grep -q "langchain-experimental" requirements/prod.txt; then
+          echo "langchain-experimental not found in requirements/prod.txt" >&2
           exit 1
         fi
 
     - name: Check for pinecone-client in requirements
       shell: bash
       run: |
-        if ! grep -q "pinecone-client" ./requirements.txt; then
-          echo "pinecone-client not found in requirements.txt" >&2
+        if ! grep -q "pinecone-client" requirements/prod.txt; then
+          echo "pinecone-client not found in requirements/prod.txt" >&2
           exit 1
         fi
 
@@ -63,7 +63,7 @@ runs:
       uses: actions/cache@v3
       with:
         path: ~/.cache/pip
-        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
+        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements/prod.txt') }}
         restore-keys: |
           ${{ runner.os }}-pip
 
@@ -85,7 +85,7 @@ runs:
     - name: Install dependencies
       shell: bash
       run: |
-        pip install -r ./requirements.txt
+        pip install -r requirements/prod.txt
       env:
         SITE_PACKAGES_PATH: ${{ env.SITE_PACKAGES_PATH }}
 
